name: models
description: Data models used by the gallery widgets
dependencies:
  collection: ^1.9.1
  intl: ^0.14.0
  quiver: ^0.21.4
  util:
    path: ../util
dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
